# Generated by Django 6.0.3 on 2026-08-28 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='gcash_name',
            field=models.CharField(blank=True, default='LEAF MPC', max_length=100),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='gcash_number',
            field=models.CharField(blank=True, default='0967-006-3500', max_length=20),
        ),
    ]
