# Generated by Django 6.0.3 on 2026-08-17 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0011_onlineapplication_id_back_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leafmemberinfo',
            name='beneficiary_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='leafmemberinfo',
            name='beneficiary_relationship',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='leafmemberinfo',
            name='credit_references',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='leafmemberinfo',
            name='no_of_dependants',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leafmemberinfo',
            name='place_of_birth',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='leafmemberinfo',
            name='religious_social_affiliation',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='leafmemberinfo',
            name='sex',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='leafmemberinfo',
            name='spouse_income',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='leafmemberinfo',
            name='spouse_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='leafmemberinfo',
            name='spouse_occupation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='leafmemberinfo',
            name='sss_gsis_no',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='leafmemberinfo',
            name='tin_no',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='onlineapplication',
            name='beneficiary_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='onlineapplication',
            name='beneficiary_relationship',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='onlineapplication',
            name='credit_references',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='onlineapplication',
            name='no_of_dependants',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='onlineapplication',
            name='place_of_birth',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='onlineapplication',
            name='religious_social_affiliation',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='onlineapplication',
            name='sex',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='onlineapplication',
            name='spouse_income',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='onlineapplication',
            name='spouse_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='onlineapplication',
            name='spouse_occupation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='onlineapplication',
            name='sss_gsis_no',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='onlineapplication',
            name='tin_no',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='member',
            name='membership_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Suspended', 'Suspended'), ('Deactivated', 'Deactivated')], default='Active', max_length=20),
        ),
    ]
