# Generated by Django 6.0.3 on 2026-09-03 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_leafmemberinfo_beneficiary_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='loan_multiplier',
            field=models.PositiveSmallIntegerField(choices=[(1, '1× — First loan'), (2, '2× — Bad payment history'), (3, '3× — Good payment history')], default=1),
        ),
    ]
