# Generated by Django 6.0.3 on 2026-08-25 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_gcashpaymentrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='released_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='released_by',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
