# Generated by Django 6.0.3 on 2026-08-25 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_loan_released_at_loan_released_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('For Review', 'For Review'), ('Approved', 'Approved'), ('Active', 'Active'), ('Completed', 'Completed'), ('Declined', 'Declined'), ('Overdue', 'Overdue'), ('Cancelled', 'Cancelled')], default='For Review', max_length=15),
        ),
    ]
