# Generated by Django 6.0.3 on 2026-09-06 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0004_alter_loan_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='months_overdue_penalized',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_type',
            field=models.CharField(choices=[('Regular Loan', 'Regular Loan'), ('Petty Cash Loan', 'Petty Cash Loan'), ('Appliance Loan', 'Appliance Loan'), ('ATM Loan', 'ATM Loan')], max_length=20),
        ),
    ]
