# Generated by Django 6.0.3 on 2026-09-07 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0005_loan_months_overdue_penalized_alter_loan_loan_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='gcashpaymentrequest',
            name='paid_to_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='gcashpaymentrequest',
            name='paid_to_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
